<a href="https://colab.research.google.com/github/mahnooshr/learning/blob/main/Data%20Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preliminaries
##Data Manipulation

<details>
  <summary>Getting Started</summary>
  <p>This is an initial version of our journey in deep learning code</p>
</details>

In [4]:
import torch

In [6]:
x=torch.arange(10, dtype=torch.float64)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [7]:
x.numel()

10

In [8]:
x=x.reshape(5,2)
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)

In [9]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [11]:
torch.rand(3,5)

tensor([[0.8113, 0.9495, 0.4007, 0.5443, 0.7093],
        [0.1547, 0.5261, 0.5460, 0.6203, 0.1085],
        [0.8506, 0.2126, 0.9356, 0.5652, 0.5360]])

In [12]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

##Indexing and Slicing

In [13]:
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)

In [14]:
x[-1]

tensor([8., 9.], dtype=torch.float64)

In [15]:
x[2:4]

tensor([[4., 5.],
        [6., 7.]], dtype=torch.float64)

In [18]:
x[3,1]

tensor(7., dtype=torch.float64)

In [19]:
x[3,1]=10
x

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [23]:
x[:3,:]=7
x

tensor([[ 7.,  7.],
        [ 7.,  7.],
        [ 7.,  7.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [28]:
x[:3,:2]=5
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

##Operations

In [29]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])
a + b, a - b, a * b, a / b, a ** b

(tensor([ 6,  8, 10, 12]),
 tensor([-4, -4, -4, -4]),
 tensor([ 5, 12, 21, 32]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([    1,    64,  2187, 65536]))

In [31]:
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [30]:
torch.exp(x)

tensor([[  148.4132,   148.4132],
        [  148.4132,   148.4132],
        [  148.4132,   148.4132],
        [  403.4288, 22026.4658],
        [ 2980.9580,  8103.0839]], dtype=torch.float64)

In [38]:
a=torch.arange(12).reshape(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [48]:
k=torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
k

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [52]:
a == k

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [49]:
torch.cat((a, k), dim=0), torch.cat((k, a), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 2.,  1.,  4.,  3.,  0.,  1.,  2.,  3.],
         [ 1.,  2.,  3.,  4.,  4.,  5.,  6.,  7.],
         [ 4.,  3.,  2.,  1.,  8.,  9., 10., 11.]]))

In [53]:
a.sum()

tensor(66)

##Broadcasting

In [55]:
m=torch.arange(3).reshape(1,3)
m

tensor([[0, 1, 2]])

In [56]:
n=torch.arange(5).reshape(5,1)
n

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [57]:
m+n

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

##Saving Memory

In [59]:
before = id(m)
m = m + n
id(m) == before

False

In [70]:
before = id(m)
m += n
id(m) == before

True

In [65]:
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [64]:
t=torch.ones_like(x)
t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [61]:
print(id(t))

136976083066832


In [66]:
t[:]=t+x
t

tensor([[ 6.,  6.],
        [ 6.,  6.],
        [ 6.,  6.],
        [ 7., 11.],
        [ 9., 10.]], dtype=torch.float64)

In [67]:
print(id(t))

136979203216528


##Conversion to Other Python Objects

In [72]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [73]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##Exercises

###1

In [74]:
X=torch.arange(20).reshape(4,5)
X

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
C =torch.ones_like(X)
C

In [85]:
C==X,Y>C,Y<C

(tensor([[False,  True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 tensor([[False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]),
 tensor([[ True, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]))

###2

In [87]:
r=torch.arange(4).reshape(4,1)
r

tensor([[0],
        [1],
        [2],
        [3]])

In [88]:
e=torch.arange(3).reshape(1,3)
e

tensor([[0, 1, 2]])

In [89]:
r+e

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')