<a href="https://colab.research.google.com/github/mahnooshr/learning/blob/main/Preliminaries.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Preliminaries
##Data Manipulation

<details>
  <summary>Getting Started</summary>
  <p>This is an initial version of our journey in deep learning code</p>
</details>

In [ ]:
import torch

In [ ]:
x=torch.arange(10, dtype=torch.float64)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

In [ ]:
x.numel()

10

In [ ]:
x=x.reshape(5,2)
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones(1,2,3)

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
torch.rand(3,5)

tensor([[0.8113, 0.9495, 0.4007, 0.5443, 0.7093],
        [0.1547, 0.5261, 0.5460, 0.6203, 0.1085],
        [0.8506, 0.2126, 0.9356, 0.5652, 0.5360]])

In [ ]:
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

##Indexing and Slicing

In [ ]:
x

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)

In [ ]:
x[-1]

tensor([8., 9.], dtype=torch.float64)

In [ ]:
x[2:4]

tensor([[4., 5.],
        [6., 7.]], dtype=torch.float64)

In [ ]:
x[3,1]

tensor(7., dtype=torch.float64)

In [ ]:
x[3,1]=10
x

tensor([[ 0.,  1.],
        [ 2.,  3.],
        [ 4.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
x[:3,:]=7
x

tensor([[ 7.,  7.],
        [ 7.,  7.],
        [ 7.,  7.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
x[:3,:2]=5
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

##Operations

In [ ]:
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([5, 6, 7, 8])
a + b, a - b, a * b, a / b, a ** b

(tensor([ 6,  8, 10, 12]),
 tensor([-4, -4, -4, -4]),
 tensor([ 5, 12, 21, 32]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([    1,    64,  2187, 65536]))

In [ ]:
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
torch.exp(x)

tensor([[  148.4132,   148.4132],
        [  148.4132,   148.4132],
        [  148.4132,   148.4132],
        [  403.4288, 22026.4658],
        [ 2980.9580,  8103.0839]], dtype=torch.float64)

In [ ]:
a=torch.arange(12).reshape(3,4)
a

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
k=torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
k

tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])

In [ ]:
a == k

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
torch.cat((a, k), dim=0), torch.cat((k, a), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 2.,  1.,  4.,  3.,  0.,  1.,  2.,  3.],
         [ 1.,  2.,  3.,  4.,  4.,  5.,  6.,  7.],
         [ 4.,  3.,  2.,  1.,  8.,  9., 10., 11.]]))

In [ ]:
a.sum()

tensor(66)

##Broadcasting

In [ ]:
m=torch.arange(3).reshape(1,3)
m

tensor([[0, 1, 2]])

In [ ]:
n=torch.arange(5).reshape(5,1)
n

tensor([[0],
        [1],
        [2],
        [3],
        [4]])

In [ ]:
m+n

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5],
        [4, 5, 6]])

##Saving Memory

In [ ]:
before = id(m)
m = m + n
id(m) == before

False

In [ ]:
before = id(m)
m += n
id(m) == before

True

In [ ]:
x

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
t=torch.ones_like(x)
t

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [ ]:
print(id(t))

136976083066832


In [ ]:
t[:]=t+x
t

tensor([[ 6.,  6.],
        [ 6.,  6.],
        [ 6.,  6.],
        [ 7., 11.],
        [ 9., 10.]], dtype=torch.float64)

In [ ]:
print(id(t))

136979203216528


##Convert to torch Objects

In [ ]:
A = x.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

##Exercises

###1

In [ ]:
X=torch.arange(20).reshape(4,5)
X

tensor([[ 5.,  5.],
        [ 5.,  5.],
        [ 5.,  5.],
        [ 6., 10.],
        [ 8.,  9.]], dtype=torch.float64)

In [ ]:
C =torch.ones_like(X)
C

In [ ]:
C==X,Y>C,Y<C

(tensor([[False,  True, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 tensor([[False, False,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]),
 tensor([[ True, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]))

###2

In [ ]:
r=torch.arange(4).reshape(4,1)
r

tensor([[0],
        [1],
        [2],
        [3]])

In [ ]:
e=torch.arange(3).reshape(1,3)
e

tensor([[0, 1, 2]])

In [ ]:
r+e

tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'school.csv')
with open(data_file, 'w') as f:
    f.write('''NUMSTUDENT,classType,grade
20,a,3
NA,a,5
40,NA,1
10,a,7''')

##Data Preprocessing

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv(data_file)
print(data)

   NUMSTUDENT classType  grade
0        20.0         a      3
1         NaN         a      5
2        40.0       NaN      1
3        10.0         a      7


NaN is a missing value

 imputation:replaces missing values with estimates of their values

 deletion:discards either those rows or those columns that contain missing values


In [ ]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NUMSTUDENT  classType_a  classType_nan
0        20.0            1              0
1         NaN            1              0
2        40.0            0              1
3        10.0            1              0


mean value

In [ ]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NUMSTUDENT  classType_a  classType_nan
0   20.000000            1              0
1   23.333333            1              0
2   40.000000            0              1
3   10.000000            1              0


Convert to tensor

import torch

r = torch.tensor(inputs.to_numpy(dtype=float))
e = torch.tensor(targets.to_numpy(dtype=float))
r, e

##Exercises

1

In [18]:
import pandas as pd
import os
data=pd.read_csv('/content/iris.data', names=["a","b","c","d","e"])
data.describe(include="all")

a           b           c           d            e
count   150.000000  150.000000  150.000000  150.000000          150
unique         NaN         NaN         NaN         NaN            3
top            NaN         NaN         NaN         NaN  Iris-setosa
freq           NaN         NaN         NaN         NaN           50
mean      5.843333    3.054000    3.758667    1.198667          NaN
std       0.828066    0.433594    1.764420    0.763161          NaN
min       4.300000    2.000000    1.000000    0.100000          NaN
25%       5.100000    2.800000    1.600000    0.300000          NaN
50%       5.800000    3.000000    4.350000    1.300000          NaN
75%       6.400000    3.300000    5.100000    1.800000          NaN
max       7.900000    4.400000    6.900000    2.500000          NaN

#Linear Algebra

##Vectors

In [3]:
import torch
x=torch.arange(5)
x


tensor([0, 1, 2, 3, 4])

In [4]:
len(x)


tensor(3)

In [6]:
x[-1]

tensor(4)

##Matrices

In [8]:
A=torch.arange(12).reshape(3,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
A.T

tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

symmetric

In [11]:
A = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
A == A.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [15]:
A = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B = A.clone()
A,B,id(A)==id(B)

(tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]),
 False)

In [16]:
A * B

tensor([[ 0.,  1.,  4.],
        [ 9., 16., 25.]])

In [17]:
a = 2
X = torch.arange(24).reshape(2, 3, 4)
a,X,a+X

(2,
 tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]))

In [18]:
X.sum()

tensor(276)

In [25]:
X.sum(axis=0)

tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [26]:
X.sum(axis=1)

tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [24]:
X.sum(axis=[0, 1]) == X.sum()

tensor([False, False, False, False])

In [32]:
x.sum()/X.numel()

tensor(0.4167)

In [4]:
import torch
Y=torch.arange(8).reshape(4,2)
Y

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

Cumulative Sum

In [5]:
Y.cumsum(axis=0)

tensor([[ 0,  1],
        [ 2,  4],
        [ 6,  9],
        [12, 16]])

In [12]:
x=torch.arange(3)
y=torch.arange(3)
x,y

(tensor([0, 1, 2]), tensor([0, 1, 2]))

inner product

In [13]:
torch.dot(x,y)

tensor(5)

In [14]:
torch.sum(x * y)

tensor(5)

In [17]:
A=torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
A

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
x=torch.arange(3)
x

tensor([0, 1, 2])

In [19]:
torch.mv(A, x), A@x

(tensor([ 8, 17, 26]), tensor([ 8, 17, 26]))

In [20]:
B=torch.arange(6).reshape(3,2)
B

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [21]:
torch.mm(A, B), A@B

(tensor([[16, 22],
         [34, 49],
         [52, 76]]),
 tensor([[16, 22],
         [34, 49],
         [52, 76]]))

Norms

In [24]:
u = torch.tensor([12, 13])
torch.norm(u)

RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long